/***********************************************************************
************************************************************************
**                                                                    **
**       --------------Sparking Bitmap Converter--------------        **
**     Developed for I2C LCD, an easy-to-use display tool for makers. **
**                       Joney.S@foxmail.com                          **
**                                                                    **
************************************************************************
************************************************************************
*
* Code generated by
*
*        Sparking-BitmapConverter v1.0
*        Compiled May 15 2015
*        Sparking Work Speace
*
************************************************************************
*
* Source file: Untitled Project_istockphoto-1270206672-1024x102_2021-02-17_21.32.33.jpg
* Dimensions:  39 * 59
*
************************************************************************
*/

#include "I2C_LCD.h"


#ifndef GUI_STORAGE_PTR
  #define GUI_STORAGE_PTR PROGMEM
#endif


const unsigned char GUI_STORAGE_PTR acenoki[] = {
  ________, ________, __XXXXXX, X_______, ________,
  ________, ________, __XXXX__, XX______, ________,
  ________, ________, __XXX___, _X______, ________,
  ________, ________, __XXXX__, _X______, ________,
  ________, ________, _XX_XXX_, _X______, ________,
  ________, _XX_____, _X__XXXX, X_______, ________,
  _______X, XXXXX___, XX_X___X, ________, ________,
  ______XX, X__XX___, X_XX____, ________, ________,
  ______XX, ___X____, X_XX____, ________, ________,
  ______XX, _XXX____, XXXX____, XXXXXX__, ________,
  ______X_, XXXX____, X_X____X, XX___XX_, ________,
  ______X_, XXXX____, X_XXXX_X, XX_XXXX_, ________,
  ______XX, __XX____, X_XXXXX_, XXXXX_X_, ________,
  ________, __XXX__X, X_XXXXX_, XXXX__X_, ___X____,
  ____XXXX, __XXX__X, X_XX__XX, XXXX__XX, XXXXX___,
  __XXXX_X, XX_XX_XX, _XXX__XX, X_XXXXXX, _XXXXX__,
  _XX____X, XX_XX_XX, XXXX___X, X_X__XX_, __X_XX__,
  _XX___XX, ___XX__X, X_XX__XX, XX____XX, XX__XXX_,
  _X____XX, ___XX__X, X_XXX_XX, _X____XX, XX__X_X_,
  _X___XX_, X_XXX__X, XX__XX_X, _X____XX, XXXXX_X_,
  _X_XXXX_, X_XXXXXX, X_XXXX_X, X______X, XXXXXXX_,
  _XXX__XX, _X_XXXX_, X_XXXX__, X______X, _X______,
  _______X, __XXXXX_, X_XXXX__, X_____XX, XX______,
  ________, X_X_XXX_, __XXXX_X, X_____X_, X_______,
  ________, XXXX_XXX, __X_XX_X, X____XX_, X_______,
  ________, XX_XXXXX, X_XXX__X, _____X_X, X_______,
  ________, XX__XXXX, XXXXX_XX, XXX_XX_X, ________,
  ________, XXX_XXXX, XXXXX_X_, X_XXXXXX, ________,
  __XXXXX_, XXX__XXX, XXXXX_X_, XXXXXXX_, ________,
  _XX___XX, XXX__XXX, _XXX__X_, XX_XXXX_, ________,
  _XXX_XXX, XXXX_XXX, XXXX____, XXXX_X__, ________,
  XXXXXXX_, _XXX_XX_, _XXX_X__, XXX_XX__, ________,
  X__X_XX_, _XXX__XX, XXXX_X_X, XXX_X___, ________,
  X__XXXXX, _XXX__XX, XXXXXX_X, XX_XX___, ________,
  X__XXXXX, __XXX_XX, XXXXXX_X, X__X____, ________,
  _XXXXX_X, X_XXX__X, XXX_XX_X, X_XX____, ________,
  __XX_XX_, X_XXX_XX, XXXXXXXX, _XX_____, ________,
  __X___X_, XXXXX__X, XXX_XXXX, _X______, ________,
  ______XX, XXX_XX_X, XXXXXXXX, XX______, ________,
  _______X, X_XXXXX_, _XXXXXX_, X_______, ________,
  ________, XX_XXXX_, _XX_XXXX, X_______, ________,
  ________, _XXX_XX_, _XX_XXXX, ____XXXX, ________,
  ________, _X_X_XXX, _XX_XX_X, ____X__X, ________,
  ________, _X_XX_XX, _XX_XXXX, ____XX_X, X_______,
  ____XXXX, _X_XX_XX, _XX_XXX_, __XXXXX_, X_______,
  ____XX_X, XXX_XXXX, _XX_XXX_, _XXXXXXX, X_______,
  ____XXXX, XXXXXXXX, _XX_XXXX, _XX_____, ________,
  ____XX_X, XXXX_XXX, XXX_XXX_, _X______, ________,
  _____XXX, __XX_XXX, XXX_XX__, _X______, ________,
  ________, ___XXXXX, XXX_XX__, XX______, ________,
  ________, ____XXXX, XX_XX_X_, XX______, ________,
  ________, ____XXXX, XXXXXX__, XX______, ________,
  ________, _____XXX, XXXX_XXX, X_______, ________,
  ________, ______XX, XXXX_XXX, X_______, ________,
  ________, ______XX, XXXXXXXX, ________, ________,
  ________, _______X, XXXXXXX_, ________, ________,
  ________, _______X, XXXXXX__, ________, ________,
  ________, ________, XXX_XX__, ________, ________,
  ________, ________, _XXX____, ________, ________

};

GUI_Bitmap_t bmenoki = {
  39, /* XSize */
  59, /* YSize */
  5, /* BytesPerLine */
  1, /* BitsPerPixel */
  acenoki,  /* Pointer to picture data (indices) */
};

/* *** End of file *** */
