/***********************************************************************
************************************************************************
**                                                                    **
**       --------------Sparking Bitmap Converter--------------        **
**     Developed for I2C LCD, an easy-to-use display tool for makers. **
**                       Joney.S@foxmail.com                          **
**                                                                    **
************************************************************************
************************************************************************
*
* Code generated by
*
*        Sparking-BitmapConverter v1.0
*        Compiled May 15 2015
*        Sparking Work Speace
*
************************************************************************
*
* Source file: Lions-Mane-Mushroom-Drawing.jpg
* Dimensions:  64 * 59
*
************************************************************************
*/

#include "I2C_LCD.h"


#ifndef GUI_STORAGE_PTR
  #define GUI_STORAGE_PTR PROGMEM
#endif


const unsigned char GUI_STORAGE_PTR aclionsmane[] = {
  ________, ________, ________, _____XX_, ________, ________, ________, ________,
  ________, ________, ________, __XXXXXX, X__XXX__, ________, ________, ________,
  ________, ________, ________, XXXXX__X, XXXX_X_X, ________, ________, ________,
  ________, ________, _______X, XXX_____, X_XXXXXX, XX______, ________, ________,
  ________, ________, _____XX_, ________, ________, ___XX___, ________, ________,
  ________, ________, X__XXX__, __X_____, _____X__, _____XX_, ________, ________,
  ________, _______X, __XXX___, __X_____, ___XXX__, X__XX_XX, ________, ________,
  ________, ________, _XX_X___, ________, ________, _XX____X, ________, ________,
  ________, _____X__, X_____X_, ________, ____X___, _X_____X, ________, ________,
  ________, ____X__X, X_______, _____X__, ________, XXXX_XX_, _XX_____, ________,
  ________, _____XXX, X_______, ___XX___, ____XXX_, __XXXXXX, __XX____, ________,
  ________, __XXXX_X, ________, _XX_____, _X______, ______XX, ___XXX__, ________,
  ________, ________, _X______, ___XX___, ___XXXXX, XX_XXXXX, XX__X___, ________,
  ________, XX______, ___X____, __XXXX__, _______X, ______XX, ____XX__, ________,
  ________, X_______, ________, XX____X_, _____XXX, XX______, _X___X__, ________,
  _______X, _______X, X_____XX, _____XX_, ______XX, XX__XXX_, __X_X__X, ________,
  ______X_, _X______, _____XXX, __X_X___, __X_XX_X, _XX_____, X__X__XX, X_______,
  ______X_, ___XX___, __XXXX__, ___X____, __XX__X_, __X___X_, _X_____X, ________,
  _____X__, ________, _XXXX___, _X___X__, __XX__X_, _______X, __X_X_X_, X_______,
  _____X__, ________, __X__X__, _XX___X_, XXX_XX_X, XX_X_X__, X__X_X_X, X_______,
  ________, __X____X, X__X___X, XXX___X_, XX___X_X, _XX___X_, X____X__, XX______,
  ____XX__, ____X__X, _XX___X_, XXX___XX, XX_X_X__, __XXX___, _____X__, ________,
  ____XX__, __X___XX, XX___XXX, _____XXX, X__X__X_, X_X_XX__, _X_X_X_X, _X______,
  ____XX__, _XXXXXX_, X__X_XXX, X_X_XXXX, X__XX_X_, X___XXX_, XXX_X_X_, XX______,
  ___X_X__, ____XX_X, __X_XX_X, ____XXXX, X_X_X___, XX_X_X_X, _XXX____, XXX_____,
  ____XXXX, X__X__X_, _XXXX___, _X___XXX, __X_X___, XX_X____, __X__X_X, ___X____,
  ___XX_XX, _XXX_X_X, XXXX__X_, XXXXXXXX, __XX_X_X, X__X__X_, _X__X___, XX__X___,
  ___X_XX_, XXX_X_XX, XXXX____, __X_X_XX, _XXXXX_X, XXX_X___, _X____X_, XXX__X__,
  __XXXX_X, XXXXXXXX, XXX__XX_, _X__XXXX, _XX__X__, XXX_X___, ___XXXXX, _XX__X__,
  __XXX_X_, _X_XXXXX, __XXXX_X, X__XXXX_, _XX__XX_, _XXX_X__, __X_XX_X, _XX___X_,
  _XXX_XXX, X__XXXX_, _XX_XX__, __XX_XX_, _XX_XXX_, _XXX__X_, _X__XX_X, X__X__XX,
  _XX_XXX_, __XXXXX_, _XXXX___, __XX_X__, _XXX_XX_, _XX_X_XX, ___X_XX_, XX__X__X,
  X_X_XX_X, _XXXXX__, _XXX__X_, __XX_X__, _X_X_XX_, _XXXX__X, X_X__XX_, XXX_X__X,
  X_XXX___, XXXXXX_X, XX___X__, _XX_XX__, _X_X_XX_, __XX_X_X, ___XXX_X, XXXXX___,
  ___XX__X, XXXXX__X, XX__X___, XXX_XX__, _X_XXXX_, ___X_X__, ___XXX_X, XXXX_X__,
  __XX_XX_, XXX____X, X___XX__, XXX_XX__, _X__XXXX, ___X_XX_, __XXX_X_, XXXXXX__,
  __XX_X_X, XX____XX, __XXX_XX, X_X_XX_X, XX___XXX, _X_X_XX_, X__XX_X_, XXX_XX__,
  __XXXXXX, XX_XXXXX, _XXX__XX, _XX_XX_X, XX___XX_, X__X_XX_, ___XXX__, X_X__XX_,
  _XXXX_X_, X__XXX__, __X___XX, _XXXXX_X, XX__XXXX, X__X_XXX, _X___XXX, __XX_XX_,
  _____X__, X_XXXX__, XXX_XXXX, _XXXXX__, XXX_XXXX, X__XXX_X, _XX_XXXX, X_XX_X__,
  _____X_X, __XXX__X, _X___X_X, _XXXXX__, XXX_XXXX, X__XXX_X, ___X___X, XXX_X_X_,
  ___XX___, __XX___X, _X__XX_X, _XXXXX__, XXX__X_X, X__XXX_X, X____X_X, XXX_XXX_,
  ___XX_X_, XXXX__X_, XX_XXX_X, _XXX__X_, X_X__X_X, XX_XXX_X, _XX_X___, XXX__XX_,
  ___XX_XX, XX_X__X_, X__XXX_X, _XXX__X_, __XX_X_X, XX_XX_X_, _XX_XXX_, X_X_____,
  ___XXXXX, XX_X_XXX, X__X_XXX, __XX___X, __XX_X_X, _X_X__X_, ____XXXX, __X_____,
  ___XXXXX, X___XX_X, __XX_XX_, __XX_X_X, X__XXX__, XX_X____, X___XXXX, XXX_____,
  ___XX_XX, _XXXXX_X, _XXXXXX_, ___X_X__, X__XXX__, XX_XX___, ___XXXX_, XX______,
  ___X__X_, XXX_X_XX, XXXX_X__, X____X_X, X__XXX__, XX_XX_X_, _XXXX_X_, XX______,
  ___X__XX, XXXXX_X_, XXXX_XX_, XX__XX_X, X__XXX__, XX_XX_XX, _XXXX___, XX______,
  _____XXX, XXXX__XX, XXX__XXX, XX__XX_X, X__XXX__, XX_XX__X, XXXX____, ________,
  _____XXX, XXXXX__X, X_X__XX_, XXX_XX_X, XX_XXX__, XXXXX__X, _XXX____, ________,
  ____XXX_, XX_XX__X, __X_XXXX, _XX_XXX_, _X_XX__X, XX_XX__X, __XX____, ________,
  _____X__, X__XX_XX, ____X_XX, _XX_XXX_, XX_XX__X, XX_XX__X, __XX____, ________,
  _____X__, ____XXX_, _____XXX, __X_XXX_, XX_XX_XX, XXX_X__X, __XX____, ________,
  ________, ____XX__, _____XXX, X_XXX_X_, XX_XXXXX, XXX_X___, ___X____, ________,
  ________, ____X___, _____XXX, __XX___X, X____XX_, _X_XX___, ___X____, ________,
  ________, ____X___, ______XX, __XX___X, X____XX_, ___XX___, ________, ________,
  ________, ________, ______XX, _______X, X_______, ____X___, ________, ________,
  ________, ________, ______XX, _______X, X_______, ________, ________, ________

};

GUI_Bitmap_t bmlionsmane = {
  64, /* XSize */
  59, /* YSize */
  8, /* BytesPerLine */
  1, /* BitsPerPixel */
  aclionsmane,  /* Pointer to picture data (indices) */
};

/* *** End of file *** */
