/***********************************************************************
************************************************************************
**                                                                    **
**       --------------Sparking Bitmap Converter--------------        **
**     Developed for I2C LCD, an easy-to-use display tool for makers. **
**                       Joney.S@foxmail.com                          **
**                                                                    **
************************************************************************
************************************************************************
*
* Code generated by
*
*        Sparking-BitmapConverter v1.0
*        Compiled May 15 2015
*        Sparking Work Speace
*
************************************************************************
*
* Source file: morel.jpg
* Dimensions:  23 * 60
*
************************************************************************
*/

#include "I2C_LCD.h"


#ifndef GUI_STORAGE_PTR
  #define GUI_STORAGE_PTR PROGMEM
#endif


const unsigned char GUI_STORAGE_PTR acmorel[] = {
  _______X, XXXXXX__, ________,
  ______XX, X_XXXXX_, ________,
  _____X_X, XXXX_XX_, ________,
  _____X_X, XX___XXX, ________,
  _____X_X, X__XX_XX, X_______,
  _____XXX, __XXX_XX, ________,
  ____XXXX, _XX_X__X, X_______,
  ___XX__X, _XX____X, XXXX____,
  ___X__XX, __XXX_X_, XX_X____,
  ___XXXXX, X_XXX_X_, ___X____,
  ___XXX__, __XXX___, _X_X____,
  __XXXX_X, X__XX_XX, XX_X____,
  ___XX__X, X_XXX_XX, _XXXX___,
  __XXX_XX, X_XXX___, _XXXX___,
  __XXX_XX, X_X_____, XXXX____,
  _XXXX__X, X____XX_, XXXXX___,
  __X__X__, __X__XX_, XXXXXX__,
  __XXX__X, XXX___X_, _X___XX_,
  _XX____X, X__XX_X_, _XXX__X_,
  _XXXXXXX, XX_XX___, _XXX_XX_,
  _XX_XXX_, XX___XXX, XXX__XX_,
  XX__XX__, __XX_XXX, XXXXXX__,
  X______X, XXXX____, XXXXX___,
  XXXXXX_X, XXX__X__, ____XX__,
  XXXXXXX_, ____XXX_, ____XX__,
  _X__XXX_, XXXX_X_X, X_X_XX__,
  _XXX_X__, ______XX, X___XX__,
  _XXXXX_X, XX_X_XXX, X___X_X_,
  _XXXXX_X, XXXX_XXX, X__XX_X_,
  _XXX_X__, XXXX____, _X_XXXX_,
  _X___XX_, _____XXX, X_XXXX__,
  XXXXXXX_, __XXXXXX, X_XXXX__,
  X_XXXXX_, __XXXX__, _XXX____,
  XXXXXX__, X__XXXX_, XXXX____,
  XXX_X__X, X__XXXX_, XXX_____,
  _XX_X_XX, XX__XXX_, XX______,
  __XXX_XX, XXX_XX__, XXX_____,
  ___XX___, X_XX____, XX______,
  ____XXX_, XXXXXX_X, X_______,
  ______XX, XXXXXXXX, X_______,
  ______XX, _XXXXXX_, X_______,
  ______XX, _____X__, X_______,
  _______X, _____XX_, X_______,
  _______X, ______X_, X_______,
  _______X, _____XX_, _X______,
  _______X, _____XX_, _X______,
  _______X, _____XXX, XX______,
  _______X, _____XX_, XX______,
  _______X, ____XX__, XXX_____,
  _______X, ____X___, X_X_____,
  _______X, ____X_X_, X_X_____,
  ______X_, ______X_, _XX_____,
  ______XX, _____X__, __X_____,
  ______XX, _____X__, _XXX____,
  ______X_, ____XX_X, _XXX____,
  _____XXX, _X__X_XX, XXXX____,
  _____X_X, X__XXX_X, XXXX____,
  _____X_X, X_X_X___, X__X____,
  _____X__, X__XXXX_, X__X____,
  _____X__, ____X___, X__X____

};

GUI_Bitmap_t bmmorel = {
  23, /* XSize */
  60, /* YSize */
  3, /* BytesPerLine */
  1, /* BitsPerPixel */
  acmorel,  /* Pointer to picture data (indices) */
};

/* *** End of file *** */
