/***********************************************************************
************************************************************************
**                                                                    **
**       --------------Sparking Bitmap Converter--------------        **
**     Developed for I2C LCD, an easy-to-use display tool for makers. **
**                       Joney.S@foxmail.com                          **
**                                                                    **
************************************************************************
************************************************************************
*
* Code generated by
*
*        Sparking-BitmapConverter v1.0
*        Compiled May 15 2015
*        Sparking Work Speace
*
************************************************************************
*
* Source file: oyster.jpg
* Dimensions:  58 * 58
*
************************************************************************
*/

#include "I2C_LCD.h"


#ifndef GUI_STORAGE_PTR
  #define GUI_STORAGE_PTR PROGMEM
#endif


const unsigned char GUI_STORAGE_PTR acoyster[] = {
  ________, ________, __XXXXXX, X_XXXX__, ________, ________, ________, ________,
  ________, ________, _XXXXXXX, XXXXXXX_, ________, ________, ________, ________,
  ________, _______X, XXX_XXXX, _____XXX, ___X___X, XXX_____, ________, ________,
  ________, _____XXX, XXXXX_X_, XX___XXX, XXXXXXXX, XXXXX___, ________, ________,
  ________, ____XXXX, X_____XX, __XX__XX, XXXXXXXX, XXXXXX__, ________, ________,
  ________, ____XXXX, _XX____X, ____X___, ____XXXX, XXXXXXXX, ________, ________,
  ________, ___XXXXX, _XXX____, X____X__, XX__XXXX, XXXXXXXX, X_______, ________,
  ________, ____XX__, X__XX___, _X___X__, __X_XXXX, XXXXXXXX, X_______, ________,
  ________, ___XXX__, _XX_XX__, _XX___X_, ___X_XXX, XXXXXXXX, X_______, ________,
  ________, ___XXXXX, ___X_XX_, __XX__X_, ____XX_X, _XXXXXX_, X_______, ________,
  ________, ______XX, X__XXX_X, ___X___X, ____XXXX, _XXXXXXX, X_______, ________,
  ________, _______X, XX___X__, X___X__X, ____XXXX, _XXXXXXX, ________, ________,
  ________, _______X, XXX___XX, _X__XX__, X_____XX, _XXXXXX_, ________, ________,
  ________, ________, XXXX____, XX___X__, X____XXX, _XXXX___, ________, ________,
  ________, ________, X_XXX___, _XX__X__, _X__XXXX, _XXXX___, ________, ________,
  ________, ________, __XXX___, __X___X_, _X__XXXX, _XXX____, ________, ________,
  ________, ________, ___XXX__, __XX_XX_, _X___XXX, _XXX____, ________, ________,
  ________, ________, ___XXX__, __XXXX_X, __X__XXX, _XXX____, ________, ________,
  ________, ________, ____XX__, ___X_X_X, __XX_XX_, _XXX____, ________, ________,
  ________, ________, ____XXX_, ___X__XX, __X__XX_, XXX_____, ________, ________,
  ________, ________, _____XX_, X__X_X_X, X_X_XX__, XXX_____, ________, ________,
  ________, ________, ____XXXX, X__X_X__, X__XXX_X, XXX_____, XXX_____, ________,
  ________, ________, _____XXX, X__X_X__, X__XX__X, XX_____X, XXXX____, ________,
  ________, ________, ______X_, _X_XXXXX, X__XXXXX, XX____XX, XXXXX___, ________,
  ________, ________, _______X, XXX_XXXX, XX_XXXXX, XX_X_XX_, X_XXX___, ________,
  ________, ________, ________, XXXXXXXX, XX_XXXXX, XXXXXXX_, X_XXXX__, ________,
  ________, ________, ________, __X_XXXX, XX_XXXXX, XXXXXXX_, X_XX_X__, ________,
  ________, ________, ________, __XXXXX_, XX_XXXX_, XXXXXX__, X_XX_X__, ________,
  ________, ________, ________, ___X_XXX, XXXXXXXX, XXXXXX__, X_XX_X__, ________,
  ________, ________, ________, ___XXXXX, XXXXX__X, XXXXXX__, X_XX_X__, ________,
  ________, ________, ________, ____XXXX, XXXX_X__, _XXXX___, __XX_XX_, ________,
  ________, ________, ________, ______XX, XX_XX___, _XXX_XX_, X_X_X___, ________,
  ________, __XXXX__, ________, ______XX, XXX_X___, _XX_XX_X, X_X_XX__, ________,
  ________, _XXXXXXX, XXXXXX__, ______XX, XXX_X___, _XXXXX_X, X___XX__, ________,
  ________, XXXXXXXX, XXXXXXXX, XXX___XX, XXXX____, X_XXXX_X, X__XXX_X, XX______,
  _______X, XXXXXXXX, X__XXXXX, XXXXXXXX, XXXXX___, _XXXX_XX, X__XXXXX, XX______,
  ______XX, XX______, _____XXX, XXXXXXX_, XXXXXX__, __XXXXXX, XXXXXXXX, XX______,
  _____XXX, ___XX___, _____X__, XXX__XX_, XXXXXXX_, __XXXXXX, XXXXXXXX, _X______,
  ____XX__, _X__X___, ______X_, X____XX_, XXXXXXXX, X_XXXXXX, XXXXX___, XX______,
  ___XX___, _X__X___, X_____X_, X____X_X, XXXXXX_X, XXXXXXXX, XXXX___X, X_______,
  __XXX___, _X___XX_, _X____X_, _X___X_X, XXXXXXX_, XXXXXXXX, XXXX__XX, X_______,
  _XX__X__, __X__XX_, __XX__X_, __X__X__, _XXXXXX_, XXXXXXXX, _XXXX_XX, X_______,
  _XX___X_, __XXX_XX, ____X__X, X_X__X_X, __XXXXXX, XXXXXXXX, XXXX__XX, X_______,
  XX_X_XX_, _X_XX__X, _X___X_X, _X___XXX, X_XXXXXX, XXXX_XXX, X_XX__X_, X_______,
  X___X_XX, __X_XX__, X____X_X, X____XXX, X_XXXXXX, XXXXXXX_, _X___XXX, X_______,
  X___XXXX, X_X__XX_, XX____X_, X_____XX, X_XXXXXX, XXXXXX_X, XX_XXXXX, ________,
  X_XXXXXX, X__X_XXX, _XX__X_X, _X_____X, X_XXX_XX, XX_XX_XX, X__X_XXX, ________,
  XX_XXXXX, X___X_XX, __XXX___, XXX____X, XXXXX_XX, XXX__XX_, _____XX_, ________,
  XXXX___X, XX__X__X, X___XXX_, XXXX____, XXX_XXXX, X_______, XX__XX__, ________,
  _XXXXXXX, XXX__X_X, _XX__XX_, _X_XXX__, _XX__X_X, ____X_XX, ____X___, ________,
  __XXXXX_, __XX__XX, ___X___X, ____XX__, __XXXXXX, X____XX_, _XXX____, ________,
  ___XXXXX, X_XXXX_X, X__XX__X, XXXX_XX_, __X__XXX, XX______, XX______, ________,
  ________, ___XX_X_, XX__X___, XX___XXX, ___XXXX_, X_____XX, ________, ________,
  ________, ______XX, XXX_____, __XXX_XX, XXXXXXX_, _XXXXX__, ________, ________,
  ________, ________, _XXX__X_, X_XXXXXX, XXXXXXX_, ________, ________, ________,
  ________, ________, ____X___, _XXXXXXX, XXXXX_X_, ________, ________, ________,
  ________, ________, ____XX_X, XX__XX_X, X_______, ________, ________, ________,
  ________, ________, _____X_X, X_____X_, ________, ________, ________, ________

};

GUI_Bitmap_t bmoyster = {
  58, /* XSize */
  58, /* YSize */
  8, /* BytesPerLine */
  1, /* BitsPerPixel */
  acoyster,  /* Pointer to picture data (indices) */
};

/* *** End of file *** */
