/***********************************************************************
************************************************************************
**                                                                    **
**       --------------Sparking Bitmap Converter--------------        **
**     Developed for I2C LCD, an easy-to-use display tool for makers. **
**                       Joney.S@foxmail.com                          **
**                                                                    **
************************************************************************
************************************************************************
*
* Code generated by
*
*        Sparking-BitmapConverter v1.0
*        Compiled May 15 2015
*        Sparking Work Speace
*
************************************************************************
*
* Source file: turkey.jpg
* Dimensions:  72 * 60
*
************************************************************************
*/

#include "I2C_LCD.h"


#ifndef GUI_STORAGE_PTR
  #define GUI_STORAGE_PTR PROGMEM
#endif


const unsigned char GUI_STORAGE_PTR acrieshi1[] = {
  ________, ________, ________, ________, ________, _______X, XXX_____, ________, ________,
  ________, ________, ________, ________, ________, ____XXXX, XXXXXXXX, XXXX____, ________,
  ________, ________, ________, ________, ________, ___XX___, _XX___XX, ___XXXXX, ________,
  ________, ________, ________, ________, ________, __XX__XX, XXXXXX_X, XXXX___X, X_______,
  ________, ________, ________, ________, ________, XXXXXXXX, XXX_X___, ________, _XX_____,
  ________, ________, ________, ________, ______XX, XXXXXX_X, XX____XX, XXXXXXX_, __XX____,
  ________, ________, ________, ________, ______X_, XXXXXXXX, X__XXXXX, XXX__XXX, ___X____,
  ________, ________, ________, ________, _____XX_, XXXXXXXX, XXXXXXX_, XXXXX_XX, X___X___,
  ________, ________, ________, ________, ____XX_X, XXXXXXXX, XXXXXXXX, XX_XX__X, XX__XX__,
  ________, ________, ________, _XXXX___, ____XXXX, XXXX_XXX, XXXXXXXX, XXXX_X__, XXX__X__,
  ________, ________, _____XXX, XXXXXXX_, ___XXXXX, XXX__XX_, _XXXX___, X__XXXX_, X_XX_XX_,
  ________, ________, ___XXX__, _______X, XXXXXXXX, XXX_XXXX, XXXXXXXX, X___XXX_, X_XX__X_,
  ________, ________, __XX__XX, XXX_____, ___XXXXX, XXXXXXXX, XXXXXXXX, XX__XXXX, _XXX__X_,
  ________, ________, XX__XXXX, XXXXXX__, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXX_XXX, _XXXX_XX,
  ________, _______X, X__XXXX_, __XXXXXX, XXXXXXXX, XX______, XXXXXX_X, XXXX__XX, _XXXX_XX,
  ________, ______XX, __XXX__X, XXXXXXXX, XXXXXXXX, XXXX____, XXXXXXX_, XXXXX_XX, _XX_X_XX,
  ________, _____XX_, _XXX_XX_, ___XXXXX, XXXXX___, _XXXXX__, _XXXXXXX, __XXX__X, __XXX_XX,
  ________, _____X__, XXX_XX__, XXXXXXXX, XXXXXXXX, XX_XXXX_, _XXXXXXX, XX__XX_X, __X_X_XX,
  ________, ____XX_X, X__XX_XX, XXXXXXXX, XXXXXXXX, XXXX_XXX, __XXXX__, XXXX_X_X, _XXXX_XX,
  ________, ____X_XX, X_X__XXX, XXXX__XX, XXXXXXXX, XX_XX_XX, X__XXXX_, _XXXXX_X, XXXXX_XX,
  ________, ___X__XX, _X__XXXX, ________, ___XXXXX, XXXXXX_X, XX_XXXXX, _XXXXX_X, XXXX_XX_,
  ________, __XX_XXX, X__XXXX_, __XXXXXX, XXXX_X__, XXXXXXX_, XXXXXXXX, __XXX__X, XXX__XX_,
  ________, __X__XXX, __XXX__X, XXXXXXXX, XXXXXXXX, _XXXXXXX, _XX_XXXX, X_XXX_XX, XXX_XX__,
  ________, _X__XXX_, XXXX__XX, XXX_____, _XXXXXXX, XX_XXXXX, _XX_XXXX, X_XXX_XX, X__XX___,
  ________, XX_XXX__, XXX__XXX, ______XX, XXXXXXXX, XXX_XXXX, X_XXXXXX, X_XXXXXX, XXXX____,
  _______X, X_XXXX_X, XXX_XX_X, XXXXXXXX, XXXXXXXX, XXX__XXX, X_XXXXXX, X_XXXX_X, X_______,
  _____XX_, _XXXX_XX, XX_XX__X, XXXXXXXX, XXXX_XXX, XXXX_XXX, XXXX_XXX, X_XXXX_X, ________,
  ____XX__, XXXXXXXX, __XX_XXX, XXXXXX__, ______XX, XXXX_XXX, X_XXXXXX, X_XXXXXX, ________,
  ___XX__X, XX_X_XXX, _XXXXXXX, XX___X__, ________, XXXXXXXX, X_X_XXXX, X_XXXXXX, XX______,
  ___X___X, XXX_XXX_, _XXXXXXX, XX___X_X, XX______, XXXXX_XX, XXX_XXXX, XXXXXXX_, __XX____,
  __XX_XXX, _XX_XX__, _XXXXXX_, ___XXXXX, XXXXXX__, __XXXXXX, XXX_XXXX, XXXXXXXX, XX_X____,
  __X__XX_, XX__XX__, _XXXX___, __XXXXXX, XXXXXXX_, __XXXXXX, XXX_XXXX, XXXXXXXX, XXX_X___,
  _XX_XXX_, XX_XX___, XXXX___X, XXXXXXXX, XXX_XXXX, ___XXXXX, XXX_XXXX, X______X, XXXXXX__,
  _X__XX_X, XX_XX__X, XX____XX, XXXXXX_X, X_____XX, XX__XX_X, XXXXXXXX, XXXXXX__, XXXXXX__,
  _X_XXX_X, X_XXX__X, XX____XX, XX____XX, XXXX____, XXX_XXXX, _X_XXXXX, XXXXXXX_, _XXXXXX_,
  _X_XX_XX, X_XX___X, X___XXXX, XX___XXX, XXXXXX__, XXX__XXX, _X_XXXXX, XXX__XXX, _XX_X_X_,
  XXXXX_XX, X_XX__XX, X____XXX, _____XXX, XXXXXXX_, _XXX_XXX, XX_XXXXX, XXXX__XX, _XX_X_X_,
  X__XXXXX, XXX___XX, X___XXX_, ____XXXX, XXXXXXXX, __XX_XXX, XXXX_XXX, XXXXX_XX, _XX_X_X_,
  X__XX_XX, _XX___XX, XX__XX__, _X_XXXXX, XXXXXXXX, XX_XXXXX, XXXX__XX, XXXX__XX, _XX_XXX_,
  X__XX_XX, _XXX__XX, X__XX__X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, XXXXXXX_, _XX_XXX_,
  X__XXXXX, _XXX__XX, X__XX_XX, XXX_XXXX, XXXXXXXX, XXXXXXXX, XX______, XXXXXXX_, XXX_X_X_,
  XX_XXX_X, _XXX__XX, ___XX_XX, XX_XXXXX, XXXXXXXX, XXXXXXX_, ________, XXXXXX__, XXXXXX__,
  XX_XXX_X, X_XX__XX, X_XXX_XX, _X_XXXXX, XXXXXXXX, XXXXX___, ________, XXXXXX__, XXXXXX__,
  _X_XXX_X, X_XX__XX, XXXXX___, _XXXXXXX, XXXXXXXX, XXX_____, ________, XXXXXXXX, XXXXX___,
  _X_XXX_X, X_XXX_XX, X_XXX___, XXXXXXXX, XXXX_XXX, XX______, ________, XXXXXXXX, XX______,
  _X__XXX_, X__XX_XX, X_XXX___, XXXXXXX_, X____XXX, XX______, ________, _XX_XXXX, XXXX____,
  _X__XXXX, XX__XXXX, __XXX___, XXXXX_X_, XXXXXXXX, XX______, ________, __XXXX__, XX______,
  _XX__XXX, _XX_XX_X, X_XXXX__, _XXXX___, XXXXXXXX, X_______, ________, ____XXXX, X_______,
  __X___XX, _XX_XXX_, XX_XXX__, _XXXXXX_, XXXXXXXX, X_______, ________, ________, ________,
  ___X__XX, X_XX_XX_, XXX_XXX_, _XXXXXXX, XXXXX_XX, X_______, ________, ________, ________,
  ___X___X, X__X__XX, _XX__XXX, __XXXXXX, XXXXXXX_, ________, ________, ________, ________,
  ___XX__X, XX__XX_X, X_XX__XX, XXXXXXXX, XX_XX___, ________, ________, ________, ________,
  ____X___, XXX__XX_, XX_XXX_X, XXXXXXXX, XXXX____, ________, ________, ________, ________,
  _____X__, _XXX__XX, _XXXXXXX, XXXX_XXX, XXX_____, ________, ________, ________, ________,
  _____XX_, _XXXXXXX, XXXXXXX_, XXX_X___, ________, ________, ________, ________, ________,
  ______XX, __XXXXX_, _XX__XXX, X__XX___, ________, ________, ________, ________, ________,
  _______X, X___XXXX, XXXXXXX_, ___X____, ________, ________, ________, ________, ________,
  ________, XXX___XX, XX______, _XX_____, ________, ________, ________, ________, ________,
  ________, __XXXXXX, XXXXXXXX, XX______, ________, ________, ________, ________, ________,
  ________, ____XXXX, XXXXXXXX, ________, ________, ________, ________, ________, ________

};

GUI_Bitmap_t bmrieshi = {
  72, /* XSize */
  60, /* YSize */
  9, /* BytesPerLine */
  1, /* BitsPerPixel */
  acrieshi1,  /* Pointer to picture data (indices) */
};

/* *** End of file *** */
