/***********************************************************************
************************************************************************
**                                                                    **
**       --------------Sparking Bitmap Converter--------------        **
**     Developed for I2C LCD, an easy-to-use display tool for makers. **
**                       Joney.S@foxmail.com                          **
**                                                                    **
************************************************************************
************************************************************************
*
* Code generated by
*
*        Sparking-BitmapConverter v1.0
*        Compiled May 15 2015
*        Sparking Work Speace
*
************************************************************************
*
* Source file: shiitake.jpg
* Dimensions:  39 * 50
*
************************************************************************
*/

#include "I2C_LCD.h"


#ifndef GUI_STORAGE_PTR
  #define GUI_STORAGE_PTR PROGMEM
#endif


const unsigned char GUI_STORAGE_PTR acshiitake[] = {
  ________, ________, _XXXXXXX, ________, ________,
  ________, _____XXX, __XXXXXX, XXX_____, ________,
  ________, ___XXX__, XXX_XXXX, X_XXXX__, ________,
  ________, _XXX_XXX, XXXXXXX_, _XXXXXX_, ________,
  _______X, XXXXXX__, X___XXXX, ___XXXXX, X_______,
  ______XX, XXXXXX_X, XXX_____, _X__XXXX, XX______,
  _____XXX, XXX_XXXX, XX__X___, ____XXXX, XX______,
  ____XXXX, XXXXXXXX, XX_X__X_, X___XXXX, XXX_____,
  __XXX__X, XXXX__XX, XX_X_XX_, XX___XXX, XXXX____,
  __XX__XX, XXXXXX_X, _XXXX_X_, XX____XX, XXXX____,
  _XXX_XXX, _XXXXXXX, _XXX_XX_, XXX____X, XXX_X___,
  _XX_XXXX, XXX__XX_, __X__X_X, _XXXXXX_, X_XXXX__,
  XXXXXXXX, XX___XX_, __XXXXX_, __XXXXX_, XX_XXXX_,
  XXXXXXXX, ____XXXX, _XXXXXX_, X___XX__, _X_XX_X_,
  XXXXXXX_, __XXXXX_, _XX_XXXX, ___X_XXX, X__XXXX_,
  XXXXXX__, _XXXXX__, X_X_X__X, _X_XXXXX, XX_XXXX_,
  XXXXX__X, XXXXX___, XXXXXXXX, _XX_XXX_, XXXXXXX_,
  XX_XXXXX, XXXX___X, XXXXX__X, X_X_XXX_, XXXXXXX_,
  _XXXXXXX, XXX__XXX, XXXXXXXX, XX_XXXXX, XXXXXX__,
  _XXXXXXX, X_X___X_, XXXXXXXX, XX_XXXXX, XXXXXX__,
  __XXXXXX, XXXXXXXX, X____XXX, ____XXXX, X_X_X___,
  ___XXXXX, __XXXXXX, X____XXX, X__XXXXX, _XXXX___,
  ____X__X, XX_XXXXX, XXXXXXXX, XXXXXXX_, _X______,
  ________, ___XXX__, ________, XXXXXXXX, ________,
  ________, ____X___, ________, XXXX____, ________,
  ________, ____XX__, ________, X_X_____, ________,
  ________, ____X___, ________, X_______, ________,
  ________, ____X__X, ________, XXXX____, ________,
  ________, ____X__X, ________, ____X___, ________,
  ________, ____X__X, ______XX, XXXXXXXX, ________,
  ________, ____X__X, _X_____X, _X__XXXX, XX______,
  ________, ____X__X, _X___XX_, XXXXXXXX, XXXXX___,
  ________, ____X___, _X___X_X, XXXXXXX_, XXXXXX__,
  ________, ____X___, _X___X_X, XXXXXXX_, XXXX____,
  ________, ___XX___, X____X_X, XXX__X__, XXXX_X__,
  ________, ___XX___, _____X_X, XX_XXX_X, XXXXXX__,
  ________, ___XX__X, X____XX_, XXXX__X_, _XXXXX__,
  ________, ___XX___, X_____XX, _XX_XXXX, __XXXX__,
  ________, ____X___, _X__X__X, XXXXXXXX, XXXXXX__,
  ________, ____XXXX, __X____X, __X___XX, X__XXX__,
  ________, ___XXXX_, ___X___X, ___XXXXX, _XXX____,
  ________, ___XXX__, __X____X, ______XX, XX______,
  ________, ___XXX__, XX__XXXX, ______X_, XX______,
  ________, ___XXXXX, XXXXXXXX, X______X, _X______,
  ________, ___XXXXX, XXXXXXXX, XXXXX_XX, XX______,
  ________, ___XXXXX, XXXXXXXX, XXXXXXXX, X_______,
  ________, ___XXXXX, XXXXX__X, XXXXXXXX, X_______,
  ________, ___XXXXX, XXXXXXX_, _XXXXXX_, ________,
  ________, __XXX___, _XX_____, __X_____, ________,
  ________, ________, __X_____, ________, ________

};

GUI_Bitmap_t bmshiitake = {
  39, /* XSize */
  50, /* YSize */
  5, /* BytesPerLine */
  1, /* BitsPerPixel */
  acshiitake,  /* Pointer to picture data (indices) */
};

/* *** End of file *** */
