/***********************************************************************
************************************************************************
**                                                                    **
**       --------------Sparking Bitmap Converter--------------        **
**     Developed for I2C LCD, an easy-to-use display tool for makers. **
**                       Joney.S@foxmail.com                          **
**                                                                    **
************************************************************************
************************************************************************
*
* Code generated by
*
*        Sparking-BitmapConverter v1.0
*        Compiled May 15 2015
*        Sparking Work Speace
*
************************************************************************
*
* Source file: ww.jpg
* Dimensions:  40 * 62
*
************************************************************************
*/

#include "I2C_LCD.h"


#ifndef GUI_STORAGE_PTR
  #define GUI_STORAGE_PTR PROGMEM
#endif


const unsigned char GUI_STORAGE_PTR acturkeytail[] = {
  ________, ________, __XXXXXX, XXXXX___, ___XXX__,
  ________, _______X, XXX_____, _XXXXXXX, XXXXXXX_,
  ________, ______XX, _______X, XXXXXXXX, XXXXXXXX,
  ________, _____XX_, ___XXXXX, XXXXXXXX, XXXXXXXX,
  ________, ____XX__, _XXXXXXX, XXXXXX_X, XX_XXXX_,
  ________, ___XX___, XXXXXXXX, X_______, _____XX_,
  ________, __XX___X, XXXXXX__, ___X__XX, XXX_____,
  ________, _XX___XX, XXXX___X, XXXXXXXX, XXXX____,
  ________, __XX_XXX, XX___XXX, XXXXXXXX, XXXXXX__,
  ________, __XX_XXX, X___XXXX, XX______, ___XXX__,
  ________, _XX__XXX, X__XXXXX, ________, XX__X___,
  ________, XX___XXX, __XXX___, ____XXXX, XXX_____,
  ________, X___XXX_, _XXX___X, XXXXXXXX, XXXX____,
  ________, X__XXXX_, XXX___XX, XX_XX___, ________,
  _______X, X__XXXX_, XX___XXX, ________, ________,
  ______XX, ___XXX__, XX__XXX_, ______XX, XXXX____,
  ______XX, __XXXX_X, XX_XXX__, _XXXXXXX, XXXX____,
  _____XX_, _XXXX__X, X__XX___, XXXXXXXX, XXXXX___,
  _____XX_, XXXX___X, X__X___X, XXXXXXX_, ________,
  ____XXX_, XXXX__XX, X_XX___X, XXXXX___, XXXX____,
  _____X_X, XXXX_XXX, __XX___X, XX____XX, XXXXX___,
  ____XX_X, XXX__XX_, _XXX__XX, XX___XXX, X__XX___,
  _____XXX, XXX_XXX_, _XX___XX, X__XXXXX, ________,
  _____XXX, XXX_XX__, _X___XXX, X__XXXX_, _XXX____,
  ______X_, XX__XX__, XX__XXXX, X__XXX__, XX_X____,
  ______X_, XXX_XX__, X___XXXX, X__XX_XX, X_______,
  _______X, XXXXXXXX, X___XXXX, __XXXXXX, _XX_____,
  _______X, XXXXXXXX, X__XXXX_, _XXXXXX_, XXX_____,
  ______XX, X___XXXX, ___XXX__, XXX__X_X, XXX_____,
  ___XXXXX, X___X_XX, ___XXX__, XX__XX_X, XXX_____,
  __XXX__X, X___X__X, ___XXXX_, XXXXX_XX, _XX_____,
  _XXX___X, X__XX_XX, ___XXXXX, XXXX_XX_, XXXX____,
  _X___XXX, ___XX_XX, __XXXX_X, X_X__XX_, XXXX____,
  _X__XXXX, ___XXXXX, __XXX__X, X_X__X__, XXXXX___,
  _XX_XXXX, ___XX_X_, __XXX_XX, X_XX_X__, XXXXX___,
  _X__XXXX, ___XX_X_, __XXX_XX, X_XX_XX_, _XXX____,
  _X__XXXX, ___XXXXX, ___XX_XX, X_XX__X_, __XX____,
  XX___XXX, ___XXXXX, ___XXX_X, X__XX_XX, _XX_____,
  XX___XXX, ___XXXXX, X___XXXX, XXXXX_XX, XXX_____,
  XX___XXX, XXXXXX_X, X___XXX_, XXX_XX_X, ________,
  XXX__XXX, XXXX__XX, X___XXXX, XX___X_X, __XX____,
  _XX__XXX, XX__XXX_, X___XXXX, XX_____X, XXXXX___,
  _XXX_XXX, XX_X_XX_, XX___XXX, XXX___XX, XX______,
  __XXX_XX, X_XX_XXX, XX______, XXXXXXXX, ________,
  ___XX__X, X_X_XXXX, _XX___X_, XXXXXXXX, XX______,
  ___XXXXX, X_XX_XXX, __XXXXX_, _XXXXXXX, XXX_____,
  ____XXXX, X_XX_XXX, X__XXXXX, ______XX, XXX_____,
  ____XXXX, __XX_XXX, XX____XX, _______X, _XXX____,
  ______XX, __XX__XX, XXXX__XX, XX____XX, _XXX_X__,
  ______XX, X__XX__X, XXXXX_XX, XXXXXXX_, XXXX_X__,
  _______X, X__XXX__, XXXXXX__, X__XXX__, XXXXXX__,
  _______X, XX__XXX_, _XXXXXXX, XXX___XX, XXX_XX__,
  _______X, XXX__XXX, ___XXXXX, XXXXXXXX, XX_XXX__,
  ________, XXXXX_XX, XX__XXXX, XXXXXXXX, XX_XXX__,
  ________, __XXX___, XXX_____, __XXXXXX, _XXX_XX_,
  ________, ___XXX__, _XXXX__X, X______X, XXXX_XX_,
  ________, ____XXXX, __XXXXXX, XXXXXXXX, XXX__XX_,
  ________, ______XX, X_______, XXXXXXXX, XX___XX_,
  ________, _______X, XXXXX_X_, ____XX__, ___XXX__,
  ________, ________, _XXXXXXX, _XX_____, XXXXX___,
  ________, ________, ______XX, XXXXXXXX, XX______,
  ________, ________, ________, __XXXXXX, ________

};

GUI_Bitmap_t bmturkeytail = {
  40, /* XSize */
  62, /* YSize */
  5, /* BytesPerLine */
  1, /* BitsPerPixel */
  acturkeytail,  /* Pointer to picture data (indices) */
};

/* *** End of file *** */
